# Generated by Django 5.1.3 on 2024-11-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FedExDomestic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('industry_code', models.CharField(max_length=100)),
                ('minimum_base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_zone', models.IntegerField()),
                ('end_zone', models.IntegerField()),
                ('start_weight', models.FloatField()),
                ('end_weight', models.FloatField()),
                ('discount_percent', models.FloatField()),
            ],
            options={
                'db_table': 'fedex_domestic',
            },
        ),
        migrations.CreateModel(
            name='FedExInternational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('industry_code', models.CharField(max_length=100)),
                ('minimum_base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_zone', models.IntegerField()),
                ('end_zone', models.IntegerField()),
                ('start_weight', models.FloatField()),
                ('end_weight', models.FloatField()),
                ('discount_percent', models.FloatField()),
            ],
            options={
                'db_table': 'fedex_international',
            },
        ),
        migrations.CreateModel(
            name='UPSDomestic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('industry_code', models.CharField(max_length=100)),
                ('minimum_base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_zone', models.IntegerField()),
                ('end_zone', models.IntegerField()),
                ('start_weight', models.FloatField()),
                ('end_weight', models.FloatField()),
                ('discount_percent', models.FloatField()),
            ],
            options={
                'db_table': 'ups_domestic',
            },
        ),
        migrations.CreateModel(
            name='UPSInternational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('industry_code', models.CharField(max_length=100)),
                ('minimum_base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_zone', models.IntegerField()),
                ('end_zone', models.IntegerField()),
                ('start_weight', models.FloatField()),
                ('end_weight', models.FloatField()),
                ('discount_percent', models.FloatField()),
            ],
            options={
                'db_table': 'ups_international',
            },
        ),
    ]
