# Generated by Django 5.1.3 on 2024-11-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FedExDomesticPublishedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('zone', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('published_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'fedex_domestic_published_price',
            },
        ),
    ]
